version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "public/**",
  "dist/**",
  "build/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true